version: '3.8'
services:
  calculator-app:
    image: calculator:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181